updated buildspec.yml file

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -12,11 +12,21 @@ phases:
   pre_build:
     commands:
       - "echo 'Logging in to Amazon ECR...'"
-      - "echo 'AWS Account ID: $AWS_ACCOUNT_ID'"
-      - "echo 'AWS Region: $AWS_DEFAULT_REGION'"
-      - "aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
-      - "FRONTEND_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/reblog-frontend"
-      - "BACKEND_REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/reblog-backend"
+      - |
+        if [ -z "$AWS_ACCOUNT_ID" ]; then
+          echo "Error: AWS_ACCOUNT_ID is not set"
+          exit 1
+        fi
+      - |
+        if [ -z "$AWS_DEFAULT_REGION" ]; then
+          echo "Error: AWS_DEFAULT_REGION is not set"
+          exit 1
+        fi
+      - "echo 'AWS Account ID: ${AWS_ACCOUNT_ID}'"
+      - "echo 'AWS Region: ${AWS_DEFAULT_REGION}'"
+      - "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
+      - "FRONTEND_REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/reblog-frontend"
+      - "BACKEND_REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/reblog-backend"
       - "IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)"
       - "IMAGE_TAG=${IMAGE_TAG:=latest}"
 
